In [10]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import math

# Test
# ratings=pd.read_csv(r'C:\Users\AD\Desktop\Linhtinh\miniRating.csv')

users=pd.read_csv(r'C:\Users\AD\Desktop\Linhtinh\users.dat',sep="::",names=['UserID','Gender','Age','Occupation','Zip-code'])
movies=pd.read_csv(r'C:\Users\AD\Desktop\Linhtinh\movies.dat',sep="::",names=['cache_dates=MovieID','Title','Genres'])
ratings=pd.read_csv(r'C:\Users\AD\Desktop\Linhtinh\ratings.dat',sep="::"names=['UserID','MovieID','Rating','Timestamp'])
# movies=pd.read_csv(r'C:\Users\AD\Desktop\Linhtinh\movies.csv')
# ratings=pd.read_csv(r'C:\Users\AD\Desktop\Linhtinh\ratings.csv')
# print(users.head())
# print(movies.head())
# print(ratings.head())

C:\Users\AD\AppData\Local\Temp\ipykernel_11328\3636731997.py:9: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  users=pd.read_csv(r'C:\Users\AD\Desktop\Linhtinh\users.dat',sep="::")
C:\Users\AD\AppData\Local\Temp\ipykernel_11328\3636731997.py:10: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  movies=pd.read_csv(r'C:\Users\AD\Desktop\Linhtinh\movies.dat',sep="::")
C:\Users\AD\AppData\Local\Temp\ipykernel_11328\3636731997.py:11: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); y

In [11]:

u=len(users)
m=max(movies["MovieID"])
# Test
# u=7
# m=5

# user_item=np.array([[5,5,2,0,1,np.nan,np.nan],
#                   [4,np.nan,np.nan,0,np.nan,2,np.nan],
#                   [np.nan,4,1,np.nan,np.nan,1,1],
#                   [2,2,3,4,4,np.nan,4],
#                   [2,0,4,np.nan,np.nan,np.nan,5]])
# not_seen=np.argwhere(np.isnan(user_item))
# print(not_seen)
# r_train=ratings
# user_item=np.array([[np.nan for i in range(u)] for j in range(m)])
user_item=np.full((m,u),np.nan)
r_train,r_test=train_test_split(ratings,test_size=0.1,stratify=ratings['UserID'])

r_train.head()

UserID  MovieID  Rating  Timestamp
11801       92      661       1  986187347
539662    3320      733       4  968522085
404360    2419      921       4  974247742
185118    1150     2678       1  974874113
69902      471     1215       3  976225070

In [12]:
for r in r_train.itertuples():
    user_item[r[2]-1][r[1]-1]=r[3]

user_item

array([[ 5., nan, nan, ..., nan, nan,  3.],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])

In [13]:
# for vector in user_item:
#     vector[]
mean=np.nanmean(user_item,axis=1)
for i in range(m):
    user_item[i]=user_item[i]-mean[i]

nan_cell=np.argwhere(np.isnan(user_item))

user_item=np.nan_to_num(user_item)
print(user_item)
print(mean)


# user_item=user_item-mean

C:\Users\AD\AppData\Local\Temp\ipykernel_11328\1864555427.py:3: RuntimeWarning: Mean of empty slice
  mean=np.nanmean(user_item,axis=1)


[[ 0.8535809  0.         0.        ...  0.         0.        -1.1464191]
 [ 0.         0.         0.        ...  0.         0.         0.       ]
 [ 0.         0.         0.        ...  0.         0.         0.       ]
 ...
 [ 0.         0.         0.        ...  0.         0.         0.       ]
 [ 0.         0.         0.        ...  0.         0.         0.       ]
 [ 0.         0.         0.        ...  0.         0.         0.       ]]
[4.1464191  3.21293375 3.0091954  ... 3.66666667 3.83783784 3.79821958]


In [14]:
nan_list=[[] for i in range(u)]
for cell in nan_cell:
    nan_list[cell[1]].append(cell[0])
    # print(cell[1])
    # break
nan_cell

array([[   0,    1],
       [   0,    2],
       [   0,    3],
       ...,
       [3951, 6037],
       [3951, 6038],
       [3951, 6039]], dtype=int64)

In [15]:
def similarity(x,y):
    if np.dot(x,y)==0:
        return 0
    return np.dot(x,y)/math.sqrt(np.sum(x**2)*np.sum(y**2))

In [16]:
# similarity_matrix=np.array([[None for i in range(m)] for j in range(m)])
similarity_matrix=np.full((m,m),np.nan)
# for movie_1 in range(m):
#     for movie_2 in range(movie_1+1):
#         res=similarity(user_item[movie_1],user_item[movie_2])
#         similarity_matrix[movie_1][movie_2]=res
#         similarity_matrix[movie_2][movie_1]=res

# similarity_matrix
# ans=similarity(user_item[0],user_item[4])
# ans

In [17]:
def similarity2(x,y):
    if np.dot(x,y)==0:
        return 0
    return np.dot(x,y)/math.sqrt(np.sum(x**2)*np.sum(y[x!=0]**2))


In [18]:
# similarity_matrix=np.array([[None for i in range(m)] for j in range(m)])
for movie_1 in range(m):
    for movie_2 in range(m):
        similarity_matrix[movie_1][movie_2]=similarity2(user_item[movie_1],user_item[movie_2])

similarity_matrix

array([[ 1.        ,  0.10809258,  0.0457197 , ...,  0.0220256 ,
         0.02164107,  0.02345653],
       [ 0.18157163,  1.        ,  0.09203263, ..., -0.03259058,
        -0.02335392,  0.016589  ],
       [ 0.09394219,  0.11446956,  1.        , ...,  0.06229171,
         0.03984615,  0.04162212],
       ...,
       [ 0.11938295, -0.10473926,  0.14859141, ...,  1.        ,
         0.10789549,  0.09635505],
       [ 0.24122747, -0.12268791,  0.22656122, ...,  0.11039515,
         1.        ,  0.29688709],
       [ 0.05647149,  0.02029112,  0.04199398, ...,  0.03858496,
         0.09667227,  1.        ]])

In [19]:
# def neighbors(user,movie,k):
#     copy=np.array(similarity_matrix[movie])
#     np.delete(copy,nan_list[user])
#     x=(-copy).argsort()[1:k+1]
#     return x

def predict(user,movie,k):
    copy=np.array(similarity_matrix[movie])
    np.delete(copy,nan_list[user])
    neighbor=(-copy).argsort()[1:k+1]
    # neighbor=neighbors(user,movie,k)
    similar=copy[neighbor]
    # print(similar)
    # print(np.sum(similar))
    rate=user_item.T[user][neighbor]
    # print(rate)
    if np.sum(similar)!=0:
        return (rate@similar)/np.sum(np.abs(similar))
    return 0

In [20]:
similarity_matrix=np.nan_to_num(similarity_matrix)
# predict_matrix=np.full((m,u),np.nan)
mean=np.nan_to_num(mean)
se=0
for r in r_test.itertuples():
    user_item[r[2]-1][r[1]-1]=predict(r[1]-1,r[2]-1,40)+mean[r[2]-1]
    # if np.isnan(mean[r[2]-1]):
    #     print("NaN")
    se+=(user_item[r[2]-1][r[1]-1]-r[3])**2

rmse=math.sqrt(se/len(r_test))

# x=(-similarity_matrix[0]).argsort()[1:51]
# print(similarity_matrix[0][x])
# print(x)
# np.shape(similarity_matrix[0][x])
# np.shape(user_item.T[x])
# for mo in range(m):
#     x=(-similarity_matrix[mo]).argsort()[1:21]
#     if np.sum(similarity_matrix[mo][x])!=0:
#         array=user_item[x].T@similarity_matrix[mo][x]
#         array=array/np.sum(np.abs(similarity_matrix[mo][x]))
#         predict_matrix[mo]=array
#     else:
#         predict_matrix[mo]=np.zeros(u)
# print(predict(0,3,5))

In [21]:
rmse

0.9132334094169263